language: php
php:
  - 7.0
  - 7.1

install:
  - pecl install redis
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install

services:
  - redis-server

script:
  - php vendor/bin/phpunit
